# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 210894a515a7ce5a2778843ebce5a5a5cb0b9d3c00bfa10f8aa338977be791389d71774ee6d85f32be6cda8c623f1b19d2dfd687aa31aa480a9da6e409a1dc41

test:
  secret_key_base: 78cbd499a732f1f91390ad6ca77299bade93dc1204d1d18daba1177b3feb153a8218b7570c1911e24bb91030f678983f3270c7c272a9a9a8fd4618e8cc99c0df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
